[package]
name = "schemeguardian"
version = "0.2.0-alpha.3"
authors = ["Charles Chege <charleschege@protonmail.ch>"]
edition = "2018"
description = "Secrets Authentication, Encryption and Verification Engine with Key-Value Store"
homepage = "https://github.com/charleschege/SchemeGuardian"
repository = "https://github.com/charleschege/SchemeGuardian"
license = "Apache-2.0"
keywords = ["encryption", "data-protection", "autonomous-secrets", "privacy", "embedded-security"]
categories = ["cryptography", "authentication", "embedded", "web-programming"]
readme = "README.md"

[badges]
maintenance = { status = "actively-developed" }


[dependencies]
serde = { version = "1.0.101", features = ["derive"] }
bincode = "1.1.4"
custom_codes = { path = "../custom_codes" }  #"1.2.10"
rand = "0.7"
rust-argon2 = "0.5.0"
toml = "0.5.1"
tai64 = { path = "../iqlusion/crates/tai64", features = ["serde", "zeroize"] }
timelite = "1.0.3"
sled = "0.31.0"
async-std = { version = "1.5.0", features = ["attributes"] }
blake3 = "0.2.2"
chacha20poly1305 = "0.4.1"
#jemallocator = "0.3.0"
secrecy = { version = "0.6.0", features = ["serde"] }
anyhow = "1.0.27"
constant_time_eq = "0.1.5"
aead = "0.2.0"
zeroize = { version = "1.1.0", features = ["zeroize_derive"] }
data-encoding = "2.2.0"
