[package]
name = "schemeguardian"
version = "0.1.0-alpha.1"
authors = ["Charles Chege <charleschege@protonmail.ch>"]
edition = "2018"

license = "BSD-3-Clause"

[dependencies]

# SER/DE
serde = "1.0"
serde_derive = "1.0"
bincode = "1.1.4"
serde_json = "1.0.40"

#RESPONSES AND ERROR HANDLING
custom_codes = { path = "../custom_codes" }
failure = "0.1.5"
either = "1.5"
lazy_static = "1.3.0"

#ENCRYPTION AND AUTHENTICATION PRNG
#orion = "0.14.2"
branca = "0.9.0"
cookie = "0.12.0"
rand = "0.7"

#ASYNC
#runtime = "0.3.0-alpha.6"

# I/O & FILES
toml = "0.5.1"

#FASTER I/O
#deque = "0.3.2"

# SCHEDULER
priority-queue = "0.5.4"
#evmap = "4.2.2"

#SECURE MEMORY
secrecy = { version = "0.2.2", features=["serde"] }
untrusted = "0.6.2"
#secstr = "0.3.2"
zeroize = "0.9.2"

#TIME/DATE
chrono = { version = "0.4.7", features = ["serde"] }

#COMPRESSIONS
#lz4 = "1.23.1"

#KV STORE
sled = { path = "../../lib/sled/crates/sled" }

### OPTIONAL

#FILESYSTEM ACCESS AND ENCRYPTION
#zbox = "0.8.3"

# TLS
#rustls = "0.15.2"

# CRON SCHEDULER
#clokwerk = "0.1.0"

# GLOBAL ALLOCATOR
#jemallocator = "0.3.0"

# ENCRYPTION
#libflate = "0.1.25"

#EMAIL SERVICES
#lettre = "0.9.2"
#lettre_email = "0.9.2"

# ACTORS
#riker = "0.3.0"

#CLI
#color-backtrace = "0.1.3"