[package]
name = "schemeguardian"
version = "0.1.0-alpha.1"
authors = ["Charles Chege <charleschege@protonmail.ch>"]
edition = "2018"
description = "Secrets Authentication, Encryption and Verification Engine with Key-Value Store"
homepage = "https://github.com/charleschege/SchemeGuardian"
repository = "https://github.com/charleschege/SchemeGuardian"

license = "Apache-2.0"

[dependencies]

# SER/DE
serde = "1.0"
serde_derive = "1.0"
bincode = "1.1.4"
serde_json = "1.0.40"

#RESPONSES AND ERROR HANDLING
custom_codes = "1.0.3"
failure = "0.1.5"
either = "1.5"
lazy_static = "1.3.0"

#ENCRYPTION AND AUTHENTICATION PRNG
#orion = "0.14.2"
branca = "0.9.0"
rand = "0.7"
rusty_ulid = "0.9.0"
rust-argon2 = "0.5.0"

#ASYNC
#runtime = "0.3.0-alpha.6"

# I/O & FILES
toml = "0.5.1"

#FASTER I/O
#deque = "0.3.2"

# SCHEDULER
#bucket_queue = "2.0.0"
#evmap = "4.2.2"

#SECURE MEMORY
secrecy = { version = "0.2.2", features=["serde"] }
untrusted = "0.6.2"
zeroize = "0.9.2"

#TIME/DATE
chrono = { version = "0.4.7", features = ["serde"] }

#COMPRESSIONS
#lz4 = "1.23.1"

#KV STORE
sled = "0.26.0"

### OPTIONAL

#FILESYSTEM ACCESS AND ENCRYPTION
#zbox = "0.8.3"

# TLS
#rustls = "0.15.2"

# CRON SCHEDULER
#clokwerk = "0.1.0"

# GLOBAL ALLOCATOR
#jemallocator = "0.3.0"

# ENCRYPTION
#libflate = "0.1.25"

#EMAIL SERVICES
#lettre = "0.9.2"
#lettre_email = "0.9.2"

# ACTORS
#riker = "0.3.0"

#CLI
#color-backtrace = "0.1.3"
