[package]
name = "schemeguardian"
version = "0.2.0-alpha.1"
authors = ["Charles Chege <charleschege@protonmail.ch>"]
edition = "2018"
description = "Secrets Authentication, Encryption and Verification Engine with Key-Value Store"
homepage = "https://github.com/charleschege/SchemeGuardian"
repository = "https://github.com/charleschege/SchemeGuardian"

license = "Apache-2.0"

[dependencies]

# SER/DE
serde_derive = "1.0.101"
serde = "1.0.101"
bincode = "1.1.4"

#RESPONSES AND ERROR HANDLING
custom_codes = "1.0.3"
failure = "0.1.5"
lazy_static = "1.3.0"
either = "1.5.3"

#ENCRYPTION AND AUTHENTICATION CRNG
branca = "0.9.0"
rand = "0.7"
rust-argon2 = "0.5.0"

#ASYNC
#async-std = "0.99.5"

# I/O & FILES
toml = "0.5.1"

#FASTER I/O
#deque = "0.3.2"
#rayon

# SCHEDULER
#bucket_queue = "2.0.0"
#evmap = "4.2.2"

#SECURE MEMORY
redactedsecret = { version="0.4.0", features=["serde"] }
#untrusted = "0.6.2"
#zeroize = { version = "1.0.0-pre", features =["zeroize_derive"] }

#TIME/DATE
chrono = { version = "0.4.7", features = ["serde"] }

#KV STORE
sled = "0.27.0"


#uhttp_sse = "0.5.1"

# GLOBAL ALLOCATOR
#jemallocator = "0.3.0"

#EMAIL SERVICES
#lettre = "0.9.2"
#lettre_email = "0.9.2"

#CLI
#color-backtrace = "0.1.3"
